# Establish the perturbation ranges
# [!!!] This needs to be fine tuned depending on the dataset used
fx_range: [0.95, 1.2]
fy_range: [0.95, 1.2]
cx_range: [0.95, 1.05]
cy_range: [0.95, 1.05]
k1_range: [0.85, 1.15]
k2_range: [0.85, 1.15]
p1_range: [0.85, 1.15]
p2_range: [0.85, 1.15]
k3_range: [0.85, 1.15]
